---
version: 2

updates:
  - package-ecosystem: gomod
    directory: /tests
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '07:00'
      timezone: 'Pacific/Auckland'
  - package-ecosystem: 'terraform'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '07:00'
      timezone: 'Pacific/Auckland'
