---
name: create-release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: '${{ github.ref_name }}'
          token: ${{ secrets.GITHUB_TOKEN }}
